### ISSUE TITLE
Error::InitCollisionMap:: Invalid ModelID: 12xxx

### ISSUE THREAD

**Issue by Aldisetiawan14** [Pottus/ColAndreas#100]
Please tell me how to fix 
Error::InitCollisionMap:: Invalid ModelID: 12xxx

**Comment by Crayder** [comment]
https://github.com/Pottus/ColAndreas/blob/6bca61d5e56c237ae3ef1f65fb649b5dbe86afce/src/ColObject.cpp#L381-L385

```
		if (ModelPlacements[i].Modelid > 19999)
		{
			logprintf("ERROR::InitCollisionMap::Invalid ModelID::%i", ModelPlacements[i].Modelid);
			continue;
		}
```

i.e., this only happens if the modelid is more than 19999.

**Comment by Aldisetiawan14** [comment]
> https://github.com/Pottus/ColAndreas/blob/6bca61d5e56c237ae3ef1f65fb649b5dbe86afce/src/ColObject.cpp#L381-L385
> 
> i.e., this only happens if the modelid is more than 19999.

Thnks youuu

**Comment by Crayder** [comment]
Do you have a reason for needing more than 19999?

**Comment by Aldisetiawan14** [comment]
> Do you have a reason for needing more than 19999? Will close this for now.

Done i can fix it thanks you
