### ISSUE TITLE
Collision data not found on linux

### ISSUE THREAD

**Issue by Dero12** [Pottus/ColAndreas#11]
Hi, your plugin works very well on windows, but when I put it on my debian server (installed libs etc.) and put the .cadb file in /scriptfiles/colandreas (I generated it on my windows computer and then uploaded) I am being informed that the collision data is not found. Is it a problem with chmod or sth?

**Comment by Crayder** [comment]
The name of the cadb database must be `ColAndreas.cadb`

If it's properly name it's probably a permission error.

**Comment by Dero12** [comment]
http://scr.hu/0h70/hvl05
It seems that the name is good, chmod is also correct I think.

**Comment by Crayder** [comment]
Let's not assume it's correct until you test it. I'd test it but I don't have access to linux right now!

**Comment by Dero12** [comment]
Okay, thank you for your help!

**Comment by Crayder** [comment]
Was permissions the problem? If it wasn't then the developers need to know in case it's a real problem.

**Comment by Dero12** [comment]
It's still not working, I think permissions are correct.

**Comment by Crayder** [comment]
Well, I guess the most you could do is run through your whole installation process, list each step here.

Everything is fine for me on Windows, haven't got around to Linux yet. For the latest wizard (which you obviously used, the size of the .cadb indicates the success), you MUST have the latest plugin libraries and vice versa.

**Comment by Dero12** [comment]
Oh, there was a difference in version of database and plugin, it works now, I'm sorry to waste your time.
