### ISSUE TITLE
CA_ContactTest

### ISSUE THREAD

**Issue by Crayder** [Pottus/ColAndreas#14]
I tried to add it before, but failed. I suggested it to codectile and he managed to implement it to the 'cimulator'.

https://github.com/codectile/cimulator/blob/4ada607e072b5a50b66b03551ec1fd7f49685758/src/CNatives.cpp#L500

He didn't do it how I requested but I think it works.

https://github.com/codectile/cimulator/issues/5

**Comment by codectile** [comment]
I think you should have waited for my reply here https://github.com/codectile/cimulator/issues/5#issuecomment-148547294

**Comment by Crayder** [comment]
Well of course, I mentioned that issue so you would come here and hopefully give some insight on how this would be done in ColAndreas.

**Comment by codectile** [comment]
I can give you some insight, and even an explanation how it works but I'll not be implementing it in ColAndreas because I find the source complicated. Keep in mind that, I have a plugin running on the same engine, if I implement all my features into ColAndreas the why would anyone use my plugin. Don't take me in other way, I am just being practical.

**Comment by Crayder** [comment]
The contactTest was my idea... XD
I planned on implementing it in ColAndreas way before I suggested it in cimulator...
Nobody here is trying to steal from you in anyway, don't take offense.
Now on the insight, if you just give me the basics on it I'm sure I could get it.

**Comment by codectile** [comment]
I'll be updating my source again in few minutes. Then I'll come back to you, as my source has some contact test improvements now.

**Comment by codectile** [comment]
"if you just give me the basics on it I'm sure I could get it.", there is no such thing as basic here. Do you know inhertiance in c++?

**Comment by codectile** [comment]
let me just give you the code to avoid complexity:

```c++
struct CustomCollisionSensor : public btCollisionWorld::ContactResultCallback
{
	bool collided;
	CustomCollisionSensor() : btCollisionWorld::ContactResultCallback(), hit(false) {}

	virtual btScalar addSingleResult(btManifoldPoint& cp, const btCollisionObjectWrapper* colObj0, int partId0, int index0, const btCollisionObjectWrapper* colObj1, int partId1, int index1)
	{
		collided = true;
		return 0;
	}
};
```

**Comment by Crayder** [comment]
"Do you know inheritance in c++?"

I'm pretty sure if anyone knows C++, that is one of the first things they have to know when they are playing with classes at all. Yes, basically.

**Comment by codectile** [comment]
See the code, I inherited ContactResultCallback and then I overrode addSingleResult. Tell me whether it is working or not.

**Comment by Crayder** [comment]
@codectile I just installed VS on my laptop since it's broke on my desktop. I got the code in, but it won't compile.

	struct ContactSensorCallback : public btCollisionWorld::ContactResultCallback
	{
	    bool collided;
	    CustomCollisionSensor() : btCollisionWorld::ContactResultCallback(), collided(false) {}
	
	    virtual btScalar addSingleResult(btManifoldPoint& cp, const btCollisionObjectWrapper* colObj0, int partId0, int index0, const btCollisionObjectWrapper* colObj1, int partId1, int index1)
	    {
	        collided = true;
	        return 0;
	    }
	};
	int ColAndreasWorld::performContactTest(uint16_t modelid, const btQuaternion& objectRot, const btVector3& objectPos)
	{
	    ContactSensorCallback callback;
		
		// Create the rigid body
		colindex = ModelRef[modelid];
		btDefaultMotionState* colMapObjectPosition = new btDefaultMotionState(btTransform(objectRot, objectPos));
		btRigidBody::btRigidBodyConstructionInfo meshRigidBodyCI(0, colMapObjectPosition, colObjects[colindex]->getCompoundShape(), btVector3(0, 0, 0));
		btRigidBody* colMapRigidBody = new btRigidBody(meshRigidBodyCI);
	
		// Test it
	    dynamicsWorld->contactTest(colMapRigidBody, callback);
	
		delete colMapObjectPosition;
		delete colMapRigidBody;
	
		return callback.collided;
	}

**Comment by codectile** [comment]
I just encountered a major issue and I think we have to remove the contact test function.

Just do as I say:
1. create object `19658`
2. log few raytrace results, the results would be quite weird and un-accurate.
3. create a few basketball objects where the ray had hit
4. provide me the screen shot

**Comment by oscar-broman** [comment]
> Just do as I say

Can't you just paste your test code here?

**Comment by codectile** [comment]
No I can't, I am using cimulator. The above issue is with cimulator and I am not sure of ColAndreas, that's why I wanted him to test it. I am on a extremely bad Wi-Fi so I cannot afford to download ColAndreas and test it myself.

**Comment by oscar-broman** [comment]
It's 133 KB if you do a clone without depth or click *Download ZIP* - that's less network usage than reloading this page 2 times.

**Comment by codectile** [comment]
Then I would have to download it in my phone, transfer it to my computer, build it with bullet libraries, code everything based on ColAndreas, test it and then post results here. It is better to let someone else to test it, who already uses ColAndreas. Now I think I shall care about cimulator more, as ColAndreas is not my project. I would definitely do the above things if I had enough time and good internet connection.

**Comment by Crayder** [comment]
I'll do this test later, can't atm.

So is it just that object (`19658`)? I haven't noticed any problems with any objects, and I've been using quite a few. The ContactTest function works perfectly fine for me too. I'll still test that particular object later, just busy atm.

**Comment by codectile** [comment]
Oh, I think I made ColAndreas free from that specific problem already. But contact test on only mesh comprised objects(`19658`) is kind of inaccurate.

Brief Note:

When we create a convex hull mesh for a `.col` object. Bullet deduces its complex mesh architecture to a simple mesh architecture which is nothing but a rough mesh approximation of the object. Look at this picture below.

![convex hull](https://cloud.githubusercontent.com/assets/8154609/13995296/9cf4b046-f14e-11e5-93f9-8c2d30ebf3e6.jpg)

Bullet generates something like this...(fourth face) and it only considers the red lines bounding the face/object.

So, there is a potential for inaccurate contactTest result.

**Comment by Crayder** [comment]
Yeah, but that's not a huge problem for the majority of our object selection. The collisions are already simplified a lot in the models themselves. Like trees, they are basically just prisms instead of their actual cone shape.

For TexAndreas however, this could be a lot different!
