### ISSUE TITLE
Too many objects, keeping track of Streamer ids vs ColAndreas indexes.

### ISSUE THREAD

**Issue by Crayder** [Pottus/ColAndreas#15]
Well... I have 600,000 objects so far and more coming (no more than 750,000). I was using a large array to track which streamer objects belong to which ColAndreas indexes but that's getting to be too big of a hassle with this many objects. Perhaps ColAndreas could have an "extra id" similiar to Streamer's internally and a function to set and remove it. I'd do it using streamer's but that would still require a loop so that would defeat the purpose.

**Comment by codectile** [comment]
It is possible, to set custom IDs for objects in bullet engine.

**Comment by Crayder** [comment]
Yes, it is, and that would be the perfect solution...

**Comment by codectile** [comment]
Setting the ID manually will solve the problem, I think.

**Comment by Crayder** [comment]
@codectile Using setUserPointer would be a good solution. We could create a struct with multiple extra ids and such. I'm not that good at C++, my attempt at this was a failure. Perhaps you know how to go about doing so?

**Comment by codectile** [comment]
That is the thing to do. By the way, list the data members so that I can try to implement it.

**Comment by Crayder** [comment]
Just basics like maybe an array of extraID's, objectID, and float extraID's. That would be fine. Then it'd be great if there was functions (natives) to modify and retrieve those.

**Comment by codectile** [comment]
Float extraids? I can only think of object id and index as ids what else it can be.

**Comment by Crayder** [comment]
Well, just an extraID's array would be perfectly fine.

**Comment by codectile** [comment]
I tried out with cimulator and it worked so let's see how ColAndreas goes with it. By the way, what problem did you face?

**Comment by Crayder** [comment]
Well it's just that I'm still a rather moderate in C++, I just never played with void pointers before attempting this. I'm actually pretty interested in how you will do it.

**Comment by codectile** [comment]
Oh in that case I must put proper comments in the code. Honestly speaking ColAndreas' code confuse me a lot, the authors parted their code in such a way that if you edit one file you must edit other files too. I am afraid that you can not see void pointers functioning as the authors already have rigid bodies hooked to a class so there is no point using setUserPointer. If you really want to know how void pointer works I can give you a snippet which I tested with simulator.

**Comment by Crayder** [comment]
"there is no point using setUserPointer"

So does that mean that you're not going to do it now?

	"If you really want to know how void pointer works I can give you a snippet which I tested with simulator."

I'll look at the code once it's implemented (i.e. on both cimulator and ColAndreas).

**Comment by codectile** [comment]
Actually I hooked the id to object manager without setUserPointer, it was not necessary according to me. Setting the external id is working,not tested getting the Id.

If you look at the latest release of cimulator I've hooked in-game objects to collision volumes so to make it more comfortable to understand and to achieve server-synced simulation.

**Comment by codectile** [comment]
Okay so a working raw prototype is ready. To use this feature objects must have object manager flag set to true.

**Comment by Crayder** [comment]
Yeah, otherwise the scripter wouldn't be able to handle the ID's.

**Comment by codectile** [comment]
I've forked the project and prepared a raw base code. Try out and edit those code according to your needs https://github.com/codectile/ColAndreas/commits/master

Look below how void pointer works:
```c++
//a simple struct
struct objectTracker
{
	int32_t m_objectID;
	int32_t m_extraID[10];
};
//inside a function or native
objectTracker* po = new objectTracker(); //create a memory
po->m_extraID[0] = 10; //set the data
rigidBody[params[1]]->col->setUserPointer(po); //set the pointer

//inside another function or native
objectTracker* po;
po = (objectTracker*)rigidBody[params[1]]->col->getUserPointer();
logprintf("External ID %i", po->m_extraID[0]);
//delete po; //i don't know whether bullet automatically deletes the hooked pointer or not
```

Void pointers gets converted(internally) into any type of pointer such as int, float, char, or any user define data type(class).

**Comment by Crayder** [comment]
OK, so I just implemented that. I haven't tested it yet. In theory, it should work as you said.

**Comment by Crayder** [comment]
@codectile Thanks for the help! It's working!
