### ISSUE TITLE
CA_RayCastLineID crash

### ISSUE THREAD

**Issue by NexiusTailer** [Pottus/ColAndreas#20]
So, after a long test I get the crash: if you use CA_RayCastLineID at water (20000), then instead of return that number you will see this:

> [22:22:30] [debug] Server crashed while executing creator.amx
> [22:22:31] [debug] AMX backtrace:
> [22:22:31] [debug] #0 native CA_RayCastLineID () from Colandreas.DLL
> [22:22:31] [debug] #1 00005aac in public OnPlayerUpdate (0) from creator.amx
> [22:22:31] [debug] Native backtrace:
> [22:22:31] [debug] #0 611c74cd in ?? () from plugins\Colandreas.DLL
> [22:22:31] [debug] #1 611c8b08 in ?? () from plugins\Colandreas.DLL
> [22:22:31] [debug] #2 004010b6 in ?? () from samp-server.exe
> [22:22:31] [debug] #3 6b5262ca in ?? () from plugins\crashdetect.DLL
> [22:22:31] [debug] #4 6b528b28 in ?? () from plugins\crashdetect.DLL
> [22:22:31] [debug] #5 6b5209c7 in ?? () from plugins\crashdetect.DLL
> [22:22:31] [debug] #6 6b52631a in ?? () from plugins\crashdetect.DLL
> [22:22:31] [debug] #7 69f24509 in ?? () from plugins\streamer.DLL
> [22:22:31] [debug] #8 0046bdaf in ?? () from samp-server.exe
> [22:22:31] [debug] #9 0048fb34 in ?? () from samp-server.exe
> [22:22:31] [debug] #10 773fd8ea in ?? () from C:\Windows\SYSTEM32\ntdll.dll

**Comment by NexiusTailer** [comment]
P.s. CA_RayCastLineID also return 0 if collision not found, but objects which added by CA_CreateObject also can have 0 id..

**Comment by Crayder** [comment]
P.s. CA_RayCastLineID also return 0 if collision not found, but objects which added by CA_CreateObject also can have id (index) 0..

Totally correct. I'll fix that when I get home in a few weeks or so unless someone wants to do it for me, it's pretty simple. (@Pottus?)

But about the crash, I'm not sure. Perhaps you could do some more tests. Like cast rays on `_SC` objects?

**Comment by NexiusTailer** [comment]
Any created objects didn't exist.
Unfortunately I not fully understand the problem.
With -d3 crashdetect only confirmed that the problem in this function

However, this code must crash your server:
> public OnPlayerUpdate(playerid)
> {
> 	new Float:tmp;
> 	CA_RayCastLineID(1983.875366, 555.897338, 11.122355, 2028.804321, 567.251770, -7.651627, tmp, tmp, tmp);
> 	return 1;
> }

I do not know, but the crash occurs precisely around these coordinates

**Comment by codectile** [comment]
Try this.
https://github.com/Pottus/ColAndreas/blob/master/src/DynamicWorld.cpp#L115
```c++
index = -1;
ColAndreasObjectTracker* tracker = NULL;
tracker = (ColAndreasObjectTracker*)RayCallback.m_collisionObject->getUserPointer();
if(tracker) //always be safe while manipulating pointer
    index = tracker->realIndex;
```

**Comment by Romz24** [comment]
This error is fixed, you need to close the issue.

**Comment by NexiusTailer** [comment]
Done.
