### ISSUE TITLE
ColAndreas is not working for Z position 1687.44299

### ISSUE THREAD

**Issue by Walter-Correa** [Pottus/ColAndreas#27]
I have a stunt map with some objects in the Z position 1687.44299. 
But ColAndreas is not working for it.

CA_FindZ_For2DCoord() is not working.

CA_CreateObject_SC(8040, 2320.40234, 127.52637, 1687.44299,   0.00000, 0.00000, 89.99500);

Note: For all others maps is working fine.

**Comment by Ino42O** [comment]
ops my mistake, 

replace this:
``
stock CA_FindZ_For2DCoord(Float:x, Float:y, &Float:z) 
{ 
    if(CA_RayCastLine(x, y, 700.0, x, y, -1000.0, x, y, z)) 
        return 1; 
    return 0; 
}``

with this:

``stock CA_FindZ_For2DCoord(Float:x, Float:y, &Float:z)
{ 
    if(CA_RayCastLine(x, y, 2500.0, x, y, -3500.0, x, y, z))
        return 1; 
    return 0; 
}
``

**Comment by Walter-Correa** [comment]
Thanks. Worked fine.

**Comment by Crayder** [comment]
On a side note, I never use the CA_FindZ_For2DCoord function. I always just use CA_RayCastLine for getting Z positions. You have much more control that way.
