### ISSUE TITLE
Compile errors in the release version (in releases tab)

### ISSUE THREAD

**Issue by NexiusTailer** [Pottus/ColAndreas#28]
[In the latest release](https://github.com/Pottus/ColAndreas/releases/tag/v1.4.0.3) in the include there are errors at compilation:
> ...\pawno\include\colandreas.inc(1041) : error 010: invalid function or declaration
> ...\pawno\include\colandreas.inc(1044) : error 021: symbol already defined: "CA_CreateObject_DC"
>...\pawno\include\colandreas.inc(1042) : error 010: invalid function or declaration
>...\pawno\include\colandreas.inc(1042 -- 1047) : error 021: symbol already defined: "CA_DestroyObject_DC"
>...\pawno\include\colandreas.inc(1042 -- 1047) : fatal error 107: too many error messages on one line
>
>Compilation aborted.Pawn compiler 3.2.3664	 	 	Copyright (c) 1997-2006, ITB CompuPhase
>
>
>5 Errors.

So, when we can see the next stable release?

**Comment by Crayder** [comment]
Well ya see, everytime I upload a fixed version to the release section it somehow concatenates the old version to the end of the new one. This issue has already been discussed and fixed multiple times. I guess I'm gonna have to put the include in a zip and upload the zip. I hate the extra step of extracting from a zip though...

**Comment by IstuntmanI** [comment]
Well, the download should be just like v1.3.0: two archives containing everything needed for both Windows and Linux. Downloading every file one by one can be annoying. Probably this would fix that problem too.

**Comment by NexiusTailer** [comment]
So guys, what about the new release? Several years have passed since the last one, and all merged pull requests (including some critical PRs) are not present as binaries available for download from the releases section.

**Comment by Crayder** [comment]
Eh I'm not sure where you are looking but the latest release absolutely does have binaries included.

The latest commits have not been released yet, if you want to use the latest unreleased/beta features feel free to compile it yourself.

I'll eventually get back and do some things I had planned, as soon as possible especially as we inch closer to Open.MP.

**Comment by NexiusTailer** [comment]
> Eh I'm not sure where you are looking but the latest release absolutely does have binaries included.

Take a look at first message in this issue again and you will see that people for about two years have been downloading the broken include, which gives them compile errors...


> The latest commits have not been released yet, if you want to use the latest unreleased/beta features feel free to compile it yourself.

Ok. But can I use the newest (and not broken at least) include from the latest commits with .so or .dll file from releases section?

> I'll eventually get back and do some things I had planned, as soon as possible especially as we inch closer to Open.MP.

Sorry for the skepticism, but it would be more sensible to focus on the thing that has some popularity and files available for download, than the thing which now has only promises and a repository with the https page of its site. In the end, this plugin was firstly developed for samp.

**Comment by Crayder** [comment]
I promise I've reuploaded the include multiple times, it always appends some of the other include somehow. I tell people to dow load from the repo instead. Yes, it works.

Regarding that last note, you don't get it. The point was nothing to do with the platform. If I upgrade it its going to be for both. I don't have the time right now.

**Comment by NexiusTailer** [comment]
> Regarding that last note, you don't get it. The point was nothing to do with the platform. If I upgrade it its going to be for both. I don't have the time right now.

Ah, okay. It just seemed to me that many developers who haven't released important updates for their plugins for a long time just wait for the open.mp when it start and because of this they don’t spend much time on the accumulated fixes for samp :P
Nevermind then
