### ISSUE TITLE
Include bugged

### ISSUE THREAD

**Issue by NegativeIQ** [Pottus/ColAndreas#35]
Include that is in latest realeases is bugged, there is multiple definitions of same natives and such.

**Comment by Romz24** [comment]
Unfortunately this is so, you need to manually edit it.

**Comment by Romz24** [comment]
Here is the version without error
https://github.com/Pottus/ColAndreas/blob/master/Server/include/colandreas.inc

**Comment by Pottus** [comment]
Closed
