### ISSUE TITLE
No collision data found

### ISSUE THREAD

**Issue by bigw3b** [Pottus/ColAndreas#36]
Hello there! If please, I need help. I'm having a big problem which makes me unable to launch my server. I'm running newest ColAndreas and  it's working on my localhost (Windows 7), but it doesn't work on Linux (Debian 8). I've got ColAndreas umm, like, full version, not the static one, got ColAndreas.cadb in folder scriptfiles/colandreas, but it is still telling me that there is No Collision Data Found. Please, could you help me? I'm really unhelpful, I was googling,, looking in topic on SAMP forums, looking in github's issues but there was no solution found for me. 

Thanks in advance.

**Comment by Romz24** [comment]
I had a problem because the name of the file was written in small letters, when I made the capital letters large everything began to work.
`scriptfiles/colandreas/ColAndreas.cadb`
