### ISSUE TITLE
Problem with collision

### ISSUE THREAD

**Issue by Romz24** [Pottus/ColAndreas#43]
In 0.3.7, a new building was added and the collision is poorly defined, have ideas how to fix it?

![sa-mp-035](https://user-images.githubusercontent.com/2458113/34968912-30effdc6-fa7d-11e7-86db-2415a4e1c932.png)
![lsbeachside-1b](https://user-images.githubusercontent.com/2458113/34968907-2964efd0-fa7d-11e7-87da-7a89c601ef1a.png)

**Comment by Crayder** [comment]
This isn't related to ColAndreas or collisions. That's a problem with the dff and textures.
