### ISSUE TITLE
errors on the latest include

### ISSUE THREAD

**Issue by SALegacy** [Pottus/ColAndreas#45]
C:\Users\Workstation\Desktop\MySQL\pawno\include\colandreas.inc(1041) : error 010: invalid function or declaration
C:\Users\Workstation\Desktop\MySQL\pawno\include\colandreas.inc(1044) : error 021: symbol already defined: "CA_CreateObject_DC"
C:\Users\Workstation\Desktop\MySQL\pawno\include\colandreas.inc(1042) : error 010: invalid function or declaration
C:\Users\Workstation\Desktop\MySQL\pawno\include\colandreas.inc(1042 -- 1047) : error 021: symbol already defined: "CA_DestroyObject_DC"
C:\Users\Workstation\Desktop\MySQL\pawno\include\colandreas.inc(1042 -- 1047) : fatal error 107: too many error messages on one line

**Comment by Pottus** [comment]
Closed
