### ISSUE TITLE
PathFinder on CA. Have isuess. HELP!!! Using CA in another thread

### ISSUE THREAD

**Issue by Fleynaro** [Pottus/ColAndreas#49]
I want to create a PathFinder plugin [like this](http://forum.sa-mp.com/showthread.php?t=427227) using your plugin instead of MapAndreas. I need using CA functions in **other thread**. How much safely to use Invoke? Tell me how best. I know nothing, this is my first developing

**Comment by Fleynaro** [comment]
Please, answer!
I have made this plugin:
https://github.com/Fleynaro/PathFinderCA

**Comment by Fleynaro** [comment]
It seems no one to be going answer... I need your help! Please, tell me about using your plugin in a other thread. I have created a plugin long ago for calculating a route for bot system and it doesn't work well because of some trouble related to using of CA in antoher thread through Invoke.

**Comment by Fleynaro** [comment]
please answer! plugin created, https://github.com/Fleynaro/PathFinderCA. It`s very important to get any answer from you! A few servers with bots is looking for your help.

**Comment by Fleynaro** [comment]
I want to make [AI in SAMP](https://www.youtube.com/watch?v=Vw-mqQWRmAM)

**Comment by Pottus** [comment]
Closed
