### ISSUE TITLE
Analog of PlaceObjectOnGround (or GetAABB) function from cimulator

### ISSUE THREAD

**Issue by NexiusTailer** [Pottus/ColAndreas#53]
For a long time till now I'm having a problem that doesn't allow me to place the object exactly on the ground. If I try to get its radius, then there are problems with vertically or horizontally elongated objects (like a tree or table). All I found it's an ideal variant (ready-made!) function [in the cimulator plugin](https://github.com/codectile/cimulator/blob/master/server/cimulator.inc#L620-L632), but I don't need many features from it, so I'd really like to see this function in ColAndreas, or at least get instructions on how it can be done now, if it's possible at all.

**Comment by Crayder** [comment]
Use `CA_GetModelBoundingBox`.

**Comment by Romz24** [comment]
@Crayder do you plan to add a similar function as in **cimulator plugin**? it would not be superfluous, I believe.
