### ISSUE TITLE
ColAndreas.cadb in sampctl package

### ISSUE THREAD

**Issue by TheManyula** [Pottus/ColAndreas#64]
I'm using ColAndreas via sampctl and I don't really know where to put the ColAndreas.cadb file since there is no scriptfiles folder I can put it in. So, where do I put it then?

**Comment by Crayder** [comment]
https://github.com/Pottus/ColAndreas/wiki/Instructions#installing

**Comment by TheManyula** [comment]
I've read the instructions already. The issue is that I can't just create a scriptfiles/colandreas directory and put it in there. Everytime I run the sampctl package, the scriptfiles folder in sampctl's runtime folder is recreated. That means I can't put it there either since it is deleted every time I run the package. Has anyone figured out a workaround for this?
