### ISSUE TITLE
Invisible Wall

### ISSUE THREAD

**Issue by AbyssMorgan** [Pottus/ColAndreas#74]
https://youtu.be/YXrUzpiBavA

**Comment by AmyrAhmady** [comment]
Are you using the latest version? (talking about 0.3dl)

**Comment by AbyssMorgan** [comment]
Im using SAMP 0.3.7

**Comment by AmyrAhmady** [comment]
I’m talking about plugin version

**Comment by AmyrAhmady** [comment]
And it would be cool if you show us a test script like that video

Sorry for double post, github on iPhone somehow doesnt let me tap on edit button!

**Comment by AbyssMorgan** [comment]
v1.4.1

By using this command i get collision in my objects on server model 13659, but this object does not exist
```
CMD:col_test(playerid){
	new Float:tx,Float:ty,Float:tz;
	new Float:x,Float:y,Float:z,buffer[256];
	GetPlayerPos(playerid,x,y,z);
	GetPointInFrontOfCamera3D(playerid,tx,ty,tz,300.0);
	format(buffer,sizeof(buffer),"%d",ColAndreas::RayCastLine(x,y,z,tx,ty,tz,tx,ty,tz));
	SendClientMessage(playerid,-1,buffer);
	return 1;
}
```
i fixed after remove collisions for that but still not understand why this happen
```
bigear = CA_CreateDynamicObject_DC(19362, -345.686462, 1591.979614, 75.644195, 0.000000, 0.000000, 0.000000);
SetDynamicObjectMaterial(bigear, 0, 13659, "8bars", "Upt_Fence_Mesh", 0x00000000);
bigear = CA_CreateDynamicObject_DC(19362, -347.376617, 1593.500610, 75.644195, 0.000000, 0.000000, 90.000000);
SetDynamicObjectMaterial(bigear, 0, 13659, "8bars", "Upt_Fence_Mesh", 0x00000000);
```

**Comment by Crayder** [comment]
Did you use the RemoveBuildings function?

**Comment by AmyrAhmady** [comment]
@AbyssMorgan That's why I asked for version you are using. 
Can you try that with 1.4.0 and give us results? There's a chance of refs being mixed in 1.4.1, nobody had any problem yet so maybe you are the first one who faced this.

**Comment by AbyssMorgan** [comment]
I found problem in SAOI.inc object loader have a bad modelid when create Colission, but yes in some places in LV i have invisible walls.

**Comment by shchpln** [comment]
I can also confirm this bug is still present. Kind of invisible building with model 6047 in LV. No CreateObject's or CreateDynamicObject's. ColAndreas 1.5.0 
![IMG_0741_2](https://user-images.githubusercontent.com/9640666/134373086-7f95930b-0443-4582-8cbe-9553522c3f40.jpg)
