### ISSUE TITLE
Conflict between ColAndreas v1.5.0 and YSI library

### ISSUE THREAD

**Issue by Abyss-z94** [Pottus/ColAndreas#77]
I just update from ColAndreas v1.4.0 to v1.5.0 and got this error while compiling, is that an error from my YSI library?

`
\include\YSI\internal\y_version.inc(276) : warning 219: local variable "index" shadows a variable at a preceding level

\include\YSI\y_malloc.inc(447) : warning 219: local variable "index" shadows a variable at a preceding level

\include\YSI\y_malloc.inc(488) : warning 219: local variable "index" shadows a variable at a preceding level

\include\YSI\y_malloc.inc(517) : warning 219: local variable "index" shadows a variable at a preceding level

\include\YSI\y_malloc.inc(582) : warning 219: local variable "index" shadows a variable at a preceding level

\include\YSI\y_malloc.inc(613) : warning 219: local variable "index" shadows a variable at a preceding level

\include\YSI\y_malloc.inc(641) : warning 219: local variable "index" shadows a variable at a preceding level

\include\YSI\y_hooks/impl.inc(2965) : warning 219: local variable "index" shadows a variable at a preceding level

\include\colandreas.inc(12) : warning 201: redefinition of constant/macro (symbol "COLANDREAS")
\include\colandreas.inc(452) : error 001: expected token: "-identifier-", but found ":"
\include\colandreas.inc(454) : error 020: invalid symbol name ""
\include\colandreas.inc(456) : error 010: invalid function or declaration
\include\colandreas.inc(459) : error 001: expected token: "-identifier-", but found ":"
\include\colandreas.inc(461) : error 020: invalid symbol name ""
\include\colandreas.inc(463) : error 010: invalid function or declaration
\include\colandreas.inc(474) : error 010: invalid function or declaration
\include\colandreas.inc(474) : error 055: start of function body without function header
\include\colandreas.inc(478) : error 010: invalid function or declaration
\include\colandreas.inc(490) : error 010: invalid function or declaration
\include\colandreas.inc(493) : error 001: expected token: "-identifier-", but found "-tagname-"
\include\colandreas.inc(493) : error 010: invalid function or declaration
\include\colandreas.inc(493) : error 021: symbol already defined: "Itter_AddInternal"
\include\colandreas.inc(493) : fatal error 107: too many error messages on one line
`

**Comment by Crayder** [comment]
Can you show how you have the includes in your main script?

**Comment by Abyss-z94** [comment]
This is my includes orders
![image](https://user-images.githubusercontent.com/18276778/71475462-e2558800-2812-11ea-8a61-3eff5da66a7d.png)

**Comment by Crayder** [comment]
You should try simply including `colandreas` above the YSI includes. The ColAndreas include alreadys has the COLANDREAS definition.

**Comment by Abyss-z94** [comment]
Thank you, that work now. Problem solved <3

**Comment by Abyss-z94** [comment]
I just re-run server with ColAndreas v1.5.0 were compiled before, but while i check server_log it say just load v1.4.0 not v1.5.0. Is that an error or something?

[08/01/2020 15:04:19]  Loading plugin: ColAndreas
[08/01/2020 15:04:19] *********************
[08/01/2020 15:04:19] ** Created By:     **
[08/01/2020 15:04:19] ** [uL]Chris42O    **
[08/01/2020 15:04:19] ** [uL]Slice       **
[08/01/2020 15:04:19] ** [uL]Pottus      **
[08/01/2020 15:04:19] *********************
[08/01/2020 15:04:21] Loaded collision data.
[08/01/2020 15:04:21] *********************
[08/01/2020 15:04:21]   ColAndreas Loaded
[08/01/2020 15:04:21]    v1.4.0
[08/01/2020 15:04:21] *********************
[08/01/2020 15:04:21]   Loaded.

**Comment by Crayder** [comment]
Yeah... that's a mistype. Glad your issue is resolved though lol!
