### ISSUE TITLE
FCNPC's ColAndreas doesn't detect collisions from mapped objects

### ISSUE THREAD

**Issue by DTVsamp** [Pottus/ColAndreas#78]
I know this might be something for FCNPC's github but it seems nobody answers the issues there so here I am.

I'm having an issue where CA_RayCaseLine doesn't detect collisions from objects if they aren't apart of the vanilla map.  I've tried used CA_CreateObject to generate the collision info for the mapped objects before and after CA_Init() with no changes.  Trying CA_CreateDynamicObject_DC generates a undefined symbol error, even though I have colandreas (latest version) included before FCNPC, including it after FCNPC doesn't change anything.

edit: FCNPC is latest 2.0 version

**Comment by AmyrAhmady** [comment]
Yes, I can confirm that there's an issue with that, a FCNPC related issue, not ColAndreas, wait for Ziggi, current maintainer of FCNPC, to show up and fix it

**Comment by Crayder** [comment]
To be discussed further in https://github.com/ziggi/FCNPC/issues/211
