### ISSUE TITLE
CA_IsVehicleInWater & CA_IsVehicleNearWater functions

### ISSUE THREAD

**Issue by NexiusTailer** [Pottus/ColAndreas#81]
Now there is some useful functions like CA_IsPlayerInWater, CA_IsPlayerNearWater and even CA_IsPlayerFacingWater. But what about vehicles? I think it would be nice to have similar functions for that.

**Comment by Crayder** [comment]
These functions should honestly be in their own file or released as an extensive library, but yeah I agree adding similar functions or more commonly used ColAndreas things in general too.

Any other ideas for pawn-side functions that would be good examples for users?

I was also recently considering adding a projectile path generator to the plugin.
