### ISSUE TITLE
GetTickCount64

### ISSUE THREAD

**Issue by Crayder** [Pottus/ColAndreas#9]
Operating System: Windows XP SP3, latest libraries available.
ColAndreas Version: 1.3
Server Version: 0.3.7 R2-1

	---------------------------
	samp-server.exe - Entry Point Not Found
	---------------------------
	The procedure entry point GetTickCount64 could not be located in the dynamic link library KERNEL32.dll. 
	---------------------------
	OK   
	---------------------------

**Comment by Crayder** [comment]
The solution is obvious, but the plugin should be as dynamic as it was before.

**Comment by Crayder** [comment]
And cmake when compiling in vs2010:

![image](https://cloud.githubusercontent.com/assets/9919010/9152490/39cefe26-3df9-11e5-82d4-9cfd6a56d6ef.png)

**Comment by uint32** [comment]
For some reason VS2015 refuses to target Windows XP, even after setting _WIN32_WINNT and changing the toolset to v140_xp. I compiled the project using VS2013 and it works in XP now, the downloads have been updated with the fixed dll. Please confirm if it works for you now.

Regarding that CMake error, I've changed it to a `set` like you suggested (commit 1e2b616c81b216562e00eec15e5fd4d2cdc709d9) to keep things simple..

**Comment by Crayder** [comment]
Yes, the new plugin works.

Good job with the update, do you have any other plans for it?

**Comment by Pottus** [comment]
Can this be closed ?
